export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "primary-fixed": "#e4e2e1",
              "on-primary-container": "#959494",
              "tertiary-fixed": "#e6e2de",
              "surface-container-highest": "#e5e2e1",
              "on-error": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "on-secondary": "#ffffff",
              "secondary-container": "#d2e6bc",
              "on-tertiary-fixed": "#1c1b1a",
              "tertiary-container": "#2e2d2b",
              "surface-dim": "#ddd9d8",
              "on-primary-fixed-variant": "#474747",
              "on-primary-fixed": "#1b1c1c",
              "error": "#ba1a1a",
              "on-surface": "#1c1b1b",
              "surface-tint": "#5f5e5e",
              "on-tertiary": "#ffffff",
              "outline": "#747878",
              "on-secondary-fixed-variant": "#3b4c2c",
              "inverse-on-surface": "#f4f0ef",
              "secondary": "#526442",
              "on-secondary-container": "#576846",
              "background": "#fdf8f8",
              "secondary-fixed": "#d5e9bf",
              "on-background": "#1c1b1b",
              "primary": "#181919",
              "surface-container-high": "#ebe7e7",
              "surface-container": "#f1edec",
              "primary-fixed-dim": "#c8c6c6",
              "secondary-fixed-dim": "#b9cda4",
              "on-secondary-fixed": "#111f05",
              "outline-variant": "#c4c7c7",
              "on-error-container": "#93000a",
              "surface": "#fdf8f8",
              "primary-container": "#2d2d2d",
              "on-surface-variant": "#444748",
              "inverse-primary": "#c8c6c6",
              "inverse-surface": "#313030",
              "surface-variant": "#e5e2e1",
              "on-tertiary-container": "#979491",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#484644",
              "on-primary": "#ffffff",
              "tertiary": "#191917",
              "tertiary-fixed-dim": "#c9c6c3",
              "surface-container-low": "#f7f3f2",
              "surface-bright": "#fdf8f8"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "md": "16px",
              "gutter": "24px",
              "container-max": "1140px",
              "xl": "32px",
              "lg": "24px",
              "xs": "4px",
              "sm": "8px",
              "xxl": "64px"
          },
          "fontFamily": {
              "headline-lg": ["Playfair Display"],
              "body-lg": ["Inter"],
              "headline-md": ["Playfair Display"],
              "body-md": ["Inter"],
              "headline-lg-mobile": ["Playfair Display"],
              "display-lg": ["Playfair Display"],
              "label-sm": ["Inter"],
              "label-md": ["Inter"]
          },
          "fontSize": {
              "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }],
              "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
              "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
              "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.02em", "fontWeight": "500" }]
          }
      }
  },
  plugins: [],
}
